# Generated by Django 5.2.6 on 2025-10-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chocice_text',
            new_name='choice_text',
        ),
    ]
